# Generated by Django 3.0.5 on 2020-04-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_answers_count'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvoted_questions',
            field=models.ManyToManyField(related_name='downvoted_users', to='main.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_questions',
            field=models.ManyToManyField(related_name='upvoted_users', to='main.Question'),
        ),
    ]
