# Generated by Django 3.0.5 on 2020-04-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_answer_points'),
        ('users', '0002_auto_20200418_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='downvoted_answers',
            field=models.ManyToManyField(related_name='downvoted_users', to='main.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_answers',
            field=models.ManyToManyField(related_name='upvoted_users', to='main.Answer'),
        ),
    ]
