# Generated by Django 3.0.5 on 2020-04-15 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200413_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 6, 36, 18, 969249, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
