# Generated by Django 3.0.5 on 2020-04-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
