# Generated by Django 3.0.7 on 2020-06-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_question_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
